### ISSUE TITLE
ParallelIR fails for test_sum_maximum.jl

### ISSUE THREAD

**Issue by ChunlingHu** [IntelLabs/ParallelAccelerator.jl#31]
source code:

``` .julia
importall ParallelAccelerator

@acc function find_chg(k,m,W,Wp)
        W_tmp = [abs(W[i,j] - Wp[i,j]) for i in 1:m, j in 1:k]
        s = [sum(W_tmp[:,j]) for j in 1:k]
        chg = maximum(s)
end

function main(m::Int, k::Int)
    W  = Array(Float64, m, k)
    Wp = Array(Float64, m, k)
    fill!(W, 3)
    fill!(Wp, 5)
    chg = find_chg(k,m,W,Wp)

    println("chg = ", chg)

end

main(100, 100)
```

error:
```
ERROR: LoadError: "from_expr: unknown ast :CompilerTools.LivenessAnalysis.AccessSummary"
```

**Comment by lkuper** [comment]
Here's a smaller reproducer:

``` .julia
using ParallelAccelerator

@acc function f()
    W  = zeros(5, 5)
    s = sum(W[:,3])
    s = [sum(W[:,j]) for j in 1:5]
end

f()
```

Worse, this crashes Julia:
``` .julia
using ParallelAccelerator

@acc function f()
    W  = zeros(5, 5)
    s = sum(W[:,3])
end

f()
```

**Comment by DrTodd13** [comment]
Chunling's original problem is now fixed.  Lindsey's crash isn't.  So, do we close this ticket or not?  Maybe we should keep one crash report per ticket so we don't get this issue.

**Comment by DrTodd13** [comment]
Lindsey's problem comes down to the singular dimension "3" I believe.  This is one of the things that will be fixed when the range fusion branch is ready.

**Comment by lkuper** [comment]
I can open a new issue for the crashing bug, but I'm now getting a different error from the original code.

**Comment by lkuper** [comment]
This is still failing for me locally and on Travis: https://travis-ci.org/IntelLabs/ParallelAccelerator.jl/jobs/97332811#L245
