### ISSUE TITLE
Colon ranges produce invalid C++ code

### ISSUE THREAD

**Issue by KristofferC** [IntelLabs/ParallelAccelerator.jl#8]
Trying to accelerate this function leads to invalid C++ code being produced and the compilation fails:

```jl
@acc function reduce_col(A::Matrix{Float64}, x::Vector{Float64}, col::Int)
    sum((A[:, col] .- x[:]) .* (A[:, col] .- x[:]))
end
```

Compilation errors: https://gist.github.com/KristofferC/5d4fd6cec129ffdbc729

The obvious transformation:

```jl
@acc function reduce_col2(A::Matrix{Float64}, x::Vector{Float64}, col::Int)
    r = 1:size(A, 1)
    sum((A[r, col] .- x[r]) .* (A[r, col] .- x[r]))
end
```

works.

I don't know if colon ranges are supported but if they are not, maybe it is possible to detect it and throw an error instead of producing the invalid C++ code.

**Comment by KristofferC** [comment]
Also, it seems that in this case, `ParallellAccelerator` produces significantly slower code than Julia.

```jl
function reduce_col_jul(A::Matrix{Float64}, x::Vector{Float64}, col::Int)
    r = 1:size(A, 1)
    s = 0.0
    @simd for i in r
        @inbounds s += (A[i, col] .- x[i]) * (A[i, col] .- x[i])
    end
    return s
end
```

```jl
julia> A = rand(10^7,10);

julia> x = rand(10^7);

julia> j = 3;

julia> @time reduce_col_jul(A, x, j)
  0.009318 seconds (5 allocations: 176 bytes)
1.6658787023541373e6

julia> @time reduce_col2(A, x, j)
  0.097116 seconds (35 allocations: 1.641 KB)
1.6658787023540796e6
```

**Comment by ehsantn** [comment]
Hi Kristoffer, thank you for reporting this. 

Unfortunately, ParallelAccelerator has some problems supporting ranges for multidimensional arrays. It's not too difficult to support them but we haven't gotten to it yet.

The two programs are equivalent as you mentioned but Julia is generating different ASTs probably. I will look at the ASTs and let you know.

**Comment by ehsantn** [comment]
The two ASTs are below. The problem is that Julia doesn't actually create a UnitRange object for the first program and just leaves `Main.:`. It might be because of the way we prevent inlining. Paul @ninegua what do you think? We should probably support `:` in DomainIR. I'll see if I can add it quickly.
```jl
$(Expr(:lambda, Any[:A,:x,:col], Any[Any[Any[:A,Array{Float64,2},0],Any[:x,Array{Float64,1},0],Any[:col,Int64,0]],Any[],Any[],Any[]], :(begin  # /Users/etotoni/test_range.jl, line 9:
        return (ParallelAccelerator.API.sum)(((ParallelAccelerator.API.getindex)(A::Array{Float64,2},Main.:,col::Int64)::Array{Float64,1} .- (ParallelAccelerator.API.getindex)(x::Array{Float64,1},Main.:)::Array{Float64,1})::Array{Float64,1} .* ((ParallelAccelerator.API.getindex)(A::Array{Float64,2},Main.:,col::Int64)::Array{Float64,1} .- (ParallelAccelerator.API.getindex)(x::Array{Float64,1},Main.:)::Array{Float64,1})::Array{Float64,1}::Array{Float64,1})::Float64
    end::Float64)))
```

```jl
$(Expr(:lambda, Any[:A,:x,:col], Any[Any[Any[:A,Array{Float64,2},0],Any[:x,Array{Float64,1},0],Any[:col,Int64,0],Any[:r,UnitRange{Int64},18]],Any[],Any[Int64],Any[]], :(begin  # /Users/etotoni/test_range2.jl, line 8:
        GenSym(0) = (Base.arraysize)(A::Array{Float64,2},1)::Int64
        r = $(Expr(:new, UnitRange{Int64}, 1, :(((top(getfield))(Base.Intrinsics,:select_value)::I)((Base.sle_int)(1,GenSym(0))::Bool,GenSym(0),(Base.box)(Int64,(Base.sub_int)(1,1))::Int64)::Int64))) # /Users/etotoni/test_range2.jl, line 9:
        return (ParallelAccelerator.API.sum)(((ParallelAccelerator.API.getindex)(A::Array{Float64,2},r::UnitRange{Int64},col::Int64)::Array{Float64,1} .- (ParallelAccelerator.API.getindex)(x::Array{Float64,1},r::UnitRange{Int64})::Array{Float64,1})::Array{Float64,1} .* ((ParallelAccelerator.API.getindex)(A::Array{Float64,2},r::UnitRange{Int64},col::Int64)::Array{Float64,1} .- (ParallelAccelerator.API.getindex)(x::Array{Float64,1},r::UnitRange{Int64})::Array{Float64,1})::Array{Float64,1}::Array{Float64,1})::Float64
    end::Float64)))
```

**Comment by KristofferC** [comment]
I don't think a UnitRange is created in the first method due to the `Colon` object simply being dispatched to the `getindex` method, similarly to here: https://github.com/JuliaLang/julia/blob/f1664bcf8efc4cf77da8510b2f2bac8913c2a6ad/base/array.jl#L289 

(The `UnitRange` method for `getindex` is defined right above the `Colon` method).

**Comment by ehsantn** [comment]
To prevent Julia from inlining, we replace functions like `getindex()` with our dummy version as you can see in the first AST. Therefore, `Colon` object is not created for `(:)` since Julia doesn't resolve it.

**Comment by ninegua** [comment]
Even without `@acc`, the typed AST of `reduce_col` still contains call to `unsafe_getindex(x, Main.:)` instead of using range object. So it has nothing to do with us overloading `getindex` when `@acc` is used. We simply have to support the colon operator.

**Comment by ehsantn** [comment]
@ninegua makes sense. I'm working on `:` operator. Parallel-ir needs a little bit of massaging but it should be working soon.

**Comment by ehsantn** [comment]
Handling ranges is now more generalized and `:` is also supported. The first program works and gives correct results.

**Comment by ehsantn** [comment]
The performance issue is probably because we need support for handling fusion of loops with ranges. @DrTodd13 can comment.

**Comment by KristofferC** [comment]
Since the original issue (invalid C++ code) is fixed we could either close this or leave it open to track the performance part.

I leave it up to you guys to decide.

**Comment by ehsantn** [comment]
Let's leave it open. Fusion of ranges is a known issue and @DrTodd13 is working on it. Your code is a good example.

**Comment by DrTodd13** [comment]
With a recent commit, I got the number of loops in the example above down to two.  This represents the low-hanging fruit.  There is some middle-hanging fruit that isn't that difficult to do that would get this down to just one loop.  I wonder how useful that optimization would be in general though.  We keep coming back to needing a full polyhedral model.

Shall we close this then as "good enough" or do the optimization to get down to one loop?

**Comment by ehsantn** [comment]
Thanks, Todd. I think getting down to one loop is essential since these sorts of programs are typically memory-bound and we might lose a factor of 2 in performance with an extra loop.

The pattern of this program is very common, I think. I still don't know if a full polyhedral model is necessary yet, but this is a topic for another discussion.

**Comment by DrTodd13** [comment]
I believe it should be down to one loop now.
